### PR TITLE
feat: added encrypt/decrypt support for universal client

### PR DESCRIPTION
**Pull request by lcforges**

### CODE REVIEW

**Comment by clundin25** [comment]
@lcforges It looks like the tests may not be finding any public key?

Can you follow up and resolve this later

**Review by clundin25 — DISMISSED** [review]

**Comment by lcforges** [comment]
Hi @clundin25, it looks like the test slot I declared is not the same one accessed by the GitHub workflow. Do you have any suggestions on how I can set it? I am currently trying to run this line of the script in pkcs11_test.go to get the correct slot id:

SLOT=$(pkcs11-tool --list-slots --module $SOFTHSM2_MODULE | grep  -Eo "0x[A-Fa-f0-9]+" | head -n 1)

Is this a valid approach or is there a better way?

**Comment by clundin25** [comment]
@lcforges Since the Slot ID is random, this is my suggestion. Add the slot as a param to the test similar to how go-pkcs11 gave an optional override for the SoftHSMv2 library path. 

Then specify the optional flag with the correct slot, using the command you already have. This step will be done in the GitHub Action yaml file.

**Comment by lcforges** [comment]
I introduced your suggested changes, and it resulted in the same error message I was having locally ("pkcs11: C_Initialize() CKR_CRYPTOKI_ALREADY_INITIALIZED"). I think this is good progress, as I still haven't been able to run go test -v successfully.

**Comment by clundin25** [comment]
It looks like the merge was weird. Did you fetch the remote repo before merging?

**Review by clundin25 — APPROVED** [review]

**Pull request merged**
